apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-app
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  description: >-
    This task is from feeeng/builder-base  https://github.com/Feeeenng/builder-base
  workspaces:
    - name: source
      optional: true
    - name: kubeconfig-dir
      optional: true
  results:
    - name: deploy-result
      description: deploy result
  params:
    - name: IMAGE_TAG
      description: The Liunx script to run
      type: string
      default: "uname -a"
    - name: image
      default: feeeng/builder-base:v3.3.0
    - name: MAINFEST_PATH
      type: string
      description: 'the kustomize file path'
    - name: DEPLOY_ENV
      type: string
      description: 'mainfest file env'
  steps:
    - name: cli
      image: $(params.image)
      script: |
        #!/usr/bin/env bash

        [[ "$(workspaces.kubeconfig-dir.bound)" == "true" ]] && \
        [[ -f $(workspaces.kubeconfig-dir.path)/kubeconfig ]] && \
        export KUBECONFIG=$(workspaces.kubeconfig-dir.path)/kubeconfig

        cd $(workspaces.source.path)/$(params.MAINFEST_PATH)/$(params.DEPLOY_ENV)
        kustomize edit set image docker.io/feeeng/devops-java-sample:latest=$(params.IMAGE_TAG)
        kubectl kustomize  . | envsubst| kubectl apply -f -

