FROM maven:3.5 AS builder

WORKDIR /builder

COPY . /builder/

RUN mvn -Dmaven.test.skip=true clean package


FROM java:8u92-jre-alpine

WORKDIR /home

ENV JAVA_OPTS ""

COPY --from=builder /builder/target/*.jar /home
 
ENTRYPOINT java -jar *.jar $JAVA_OPTS
