FROM maven:3.5 AS builder

WORKDIR /builder

COPY . /builder/

RUN mvn -Dmaven.test.skip=true clean package


FROM java:8u92-jre-alpine

WORKDIR /home


COPY --from=builder /builder /home

ENTRYPOINT java -jar *.jar
