apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: run-git-clone
spec:
  taskRef:
    name: git-clone
  params:
    - name: repo_url
      value: "https://github.com/Feeeenng/devops-maven-sample.git"
    
  