apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-maven-sample.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "devops-maven-sample.name" . }}
    helm.sh/chart: {{ include "devops-maven-sample.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "devops-maven-sample.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
