apiVersion: v1
kind: Service
metadata:
  labels:
    app: ks-sample
  name: ks-sample
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ks-sample
  sessionAffinity: None
  type: NodePort